variables:
  CI_DEBUG_TRACE: "true"

build:
  stage: build
  script:
    - echo $CI_PIPELINE_SOURCE
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH
      changes:
        - test.txt
      when: always
      allow_failure: true
